/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NichesRouteImport } from './routes/niches'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NichesNicheIdRouteImport } from './routes/niches.$nicheId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsProjectIdVideosVideoIdRouteImport } from './routes/projects.$projectId.videos.$videoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NichesRoute = NichesRouteImport.update({
  id: '/niches',
  path: '/niches',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NichesNicheIdRoute = NichesNicheIdRouteImport.update({
  id: '/$nicheId',
  path: '/$nicheId',
  getParentRoute: () => NichesRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdVideosVideoIdRoute =
  ProjectsProjectIdVideosVideoIdRouteImport.update({
    id: '/videos/$videoId',
    path: '/videos/$videoId',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/niches': typeof NichesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/niches/$nicheId': typeof NichesNicheIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/videos/$videoId': typeof ProjectsProjectIdVideosVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/niches': typeof NichesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/niches/$nicheId': typeof NichesNicheIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/videos/$videoId': typeof ProjectsProjectIdVideosVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/niches': typeof NichesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/niches/$nicheId': typeof NichesNicheIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/videos/$videoId': typeof ProjectsProjectIdVideosVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/niches'
    | '/settings'
    | '/niches/$nicheId'
    | '/projects/$projectId'
    | '/projects/$projectId/videos/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/niches'
    | '/settings'
    | '/niches/$nicheId'
    | '/projects/$projectId'
    | '/projects/$projectId/videos/$videoId'
  id:
    | '__root__'
    | '/'
    | '/niches'
    | '/settings'
    | '/niches/$nicheId'
    | '/projects/$projectId'
    | '/projects/$projectId/videos/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NichesRoute: typeof NichesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/niches': {
      id: '/niches'
      path: '/niches'
      fullPath: '/niches'
      preLoaderRoute: typeof NichesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/niches/$nicheId': {
      id: '/niches/$nicheId'
      path: '/$nicheId'
      fullPath: '/niches/$nicheId'
      preLoaderRoute: typeof NichesNicheIdRouteImport
      parentRoute: typeof NichesRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/videos/$videoId': {
      id: '/projects/$projectId/videos/$videoId'
      path: '/videos/$videoId'
      fullPath: '/projects/$projectId/videos/$videoId'
      preLoaderRoute: typeof ProjectsProjectIdVideosVideoIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface NichesRouteChildren {
  NichesNicheIdRoute: typeof NichesNicheIdRoute
}

const NichesRouteChildren: NichesRouteChildren = {
  NichesNicheIdRoute: NichesNicheIdRoute,
}

const NichesRouteWithChildren =
  NichesRoute._addFileChildren(NichesRouteChildren)

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdVideosVideoIdRoute: typeof ProjectsProjectIdVideosVideoIdRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdVideosVideoIdRoute: ProjectsProjectIdVideosVideoIdRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NichesRoute: NichesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
