import {
  extractCaptionTracks,
  extractPlayerResponse,
  parseTimedTextJson3,
  pickCaptionTrack,
  type CaptionTrack,
  type TranscriptSegment
} from '@shared/niches'
import { logInfo, logWarn } from './logger'

/**
 * Transcript fetch via YouTube's own caption pipeline (there is no official
 * transcript API). Primary path: the InnerTube player endpoint with the
 * ANDROID client — its caption URLs are NOT gated by the proof-of-origin
 * token that makes web-client timedtext URLs return an empty 200 (verified
 * empirically; the watch-page path broke exactly that way). The watch page
 * remains as a fallback. Parsing is pure and tested in `@shared/niches`;
 * failures return null so a batch fetch skips the videos without captions.
 */

const ANDROID_USER_AGENT = 'com.google.android.youtube/20.10.38 (Linux; U; Android 11) gzip'

const ANDROID_CLIENT = {
  clientName: 'ANDROID',
  clientVersion: '20.10.38',
  androidSdkVersion: 30,
  hl: 'en'
}

const WATCH_HEADERS = {
  'Accept-Language': 'en-US,en;q=0.9',
  // Skips the EU consent interstitial that would hide the player response.
  Cookie: 'SOCS=CAI; CONSENT=YES+1',
  'User-Agent':
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36'
}

async function captionTracksViaInnertube(videoId: string): Promise<CaptionTrack[]> {
  const response = await fetch('https://www.youtube.com/youtubei/v1/player', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'User-Agent': ANDROID_USER_AGENT },
    body: JSON.stringify({ context: { client: ANDROID_CLIENT }, videoId })
  })
  if (!response.ok) return []
  return extractCaptionTracks(await response.json())
}

async function captionTracksViaWatchPage(videoId: string): Promise<CaptionTrack[]> {
  const page = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
    headers: WATCH_HEADERS
  })
  if (!page.ok) return []
  return extractCaptionTracks(extractPlayerResponse(await page.text()))
}

export interface FetchedTranscript {
  segments: TranscriptSegment[]
  languageCode: string
  autoGenerated: boolean
}

export async function fetchTranscript(
  videoId: string,
  preferredLanguages: readonly string[]
): Promise<FetchedTranscript | null> {
  try {
    let tracks = await captionTracksViaInnertube(videoId)
    if (tracks.length === 0) tracks = await captionTracksViaWatchPage(videoId)
    const track = pickCaptionTrack(tracks, preferredLanguages)
    if (!track) {
      logInfo('transcript', `${videoId}: no caption track available`)
      return null
    }
    const url = new URL(track.baseUrl)
    url.searchParams.set('fmt', 'json3')
    const timedText = await fetch(url, { headers: { 'User-Agent': ANDROID_USER_AGENT } })
    if (!timedText.ok) {
      logWarn('transcript', `${videoId}: timedtext HTTP ${timedText.status}`)
      return null
    }
    const body = await timedText.text()
    const segments = parseTimedTextJson3(body)
    if (segments.length === 0) {
      // An empty 200 is YouTube's proof-of-origin gate — worth logging loudly:
      // if this comes back, the ANDROID client stopped being exempt.
      logWarn('transcript', `${videoId}: empty timedtext body (${body.length} bytes, POT gate?)`)
      return null
    }
    return { segments, languageCode: track.languageCode, autoGenerated: track.kind === 'asr' }
  } catch (error) {
    logWarn('transcript', `fetch failed for ${videoId}: ${String(error)}`)
    return null
  }
}
